version: '2'

services:
  postgresql:
    container_name: postgresql
    image: postgres:10.6
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_USER: event_piper
      POSTGRES_PASSWORD: event_piper
      POSTGRES_DB: event_piper
    ports:
      - 5432:5432

  service:
    container_name: event_piper
    build: .
    mem_swappiness: 0
    cpu_shares: 2048
    mem_limit: 100M
    ports:
      - 4000:4000
